### ISSUE TITLE
PSC

### ISSUE THREAD

**Issue by Inder00** [Verlikylos/vMCShop-Basic#1]
Proponuje dodanie paysafecarda, jeżeli chcesz pomocy pisz :+1:

**Comment by Verlikylos** [comment]
Obsługę PSC dodaję tylko na zamówienie ;)

**Comment by Inder00** [comment]
hehe, to nie jest trudne :D

**Comment by Verlikylos** [comment]
Nie z tego powodu dostępne tylko na zamówienie ;)
